language: python
sudo: required
dist: trusty

python:
	- "2.7"

virtualenv:
	system_site_packages: true

install:
	- sudo apt-get update
	- sudo apt-get -y install python-pyqt5
	- sudo apt-get -y install
	- sudo apt-add-repository -y ppa:js-reynaud/kicad-4
	- python setup.py install
script:
	- python setup.py test