# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/danw/Software/kicad_backannotate/kicad_backannotate/gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadBoardButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadBoardButton.setObjectName("loadBoardButton")
        self.horizontalLayout.addWidget(self.loadBoardButton)
        self.prepareSchematicButton = QtWidgets.QPushButton(self.centralwidget)
        self.prepareSchematicButton.setObjectName("prepareSchematicButton")
        self.horizontalLayout.addWidget(self.prepareSchematicButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sortOrder = QtWidgets.QComboBox(self.centralwidget)
        self.sortOrder.setObjectName("sortOrder")
        self.sortOrder.addItem("")
        self.sortOrder.addItem("")
        self.verticalLayout.addWidget(self.sortOrder)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.remapView = QtWidgets.QTableView(self.centralwidget)
        self.remapView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.remapView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.remapView.setObjectName("remapView")
        self.horizontalLayout_3.addWidget(self.remapView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boardGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardGroup.sizePolicy().hasHeightForWidth())
        self.boardGroup.setSizePolicy(sizePolicy)
        self.boardGroup.setMinimumSize(QtCore.QSize(300, 0))
        self.boardGroup.setObjectName("boardGroup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.boardGroup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.xlabel = QtWidgets.QLabel(self.boardGroup)
        self.xlabel.setObjectName("xlabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.xlabel)
        self.xvalue = QtWidgets.QLabel(self.boardGroup)
        self.xvalue.setText("")
        self.xvalue.setObjectName("xvalue")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xvalue)
        self.ylabel = QtWidgets.QLabel(self.boardGroup)
        self.ylabel.setObjectName("ylabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ylabel)
        self.yvalue = QtWidgets.QLabel(self.boardGroup)
        self.yvalue.setText("")
        self.yvalue.setObjectName("yvalue")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yvalue)
        self.unitslabel = QtWidgets.QLabel(self.boardGroup)
        self.unitslabel.setObjectName("unitslabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.unitslabel)
        self.mmRadio = QtWidgets.QRadioButton(self.boardGroup)
        self.mmRadio.setChecked(True)
        self.mmRadio.setObjectName("mmRadio")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mmRadio)
        self.inchRadio = QtWidgets.QRadioButton(self.boardGroup)
        self.inchRadio.setObjectName("inchRadio")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inchRadio)
        self.timestamplabel = QtWidgets.QLabel(self.boardGroup)
        self.timestamplabel.setObjectName("timestamplabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.timestamplabel)
        self.timestampvalue = QtWidgets.QLabel(self.boardGroup)
        self.timestampvalue.setText("")
        self.timestampvalue.setObjectName("timestampvalue")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timestampvalue)
        self.footprintlabel = QtWidgets.QLabel(self.boardGroup)
        self.footprintlabel.setObjectName("footprintlabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.footprintlabel)
        self.footprintvalue = QtWidgets.QLabel(self.boardGroup)
        self.footprintvalue.setText("")
        self.footprintvalue.setObjectName("footprintvalue")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.footprintvalue)
        self.verticalLayout_2.addWidget(self.boardGroup)
        self.schGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.schGroup.setObjectName("schGroup")
        self.formLayout_3 = QtWidgets.QFormLayout(self.schGroup)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.schfilelabel = QtWidgets.QLabel(self.schGroup)
        self.schfilelabel.setObjectName("schfilelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.schfilelabel)
        self.schfilevalue = QtWidgets.QLabel(self.schGroup)
        self.schfilevalue.setText("")
        self.schfilevalue.setObjectName("schfilevalue")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.schfilevalue)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.verticalLayout_2.addWidget(self.schGroup)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.commitboardbutton = QtWidgets.QPushButton(self.centralwidget)
        self.commitboardbutton.setObjectName("commitboardbutton")
        self.horizontalLayout_2.addWidget(self.commitboardbutton)
        self.writeSchematicButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeSchematicButton.setObjectName("writeSchematicButton")
        self.horizontalLayout_2.addWidget(self.writeSchematicButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kicad backannotate"))
        self.loadBoardButton.setText(_translate("MainWindow", "Load Board"))
        self.prepareSchematicButton.setText(_translate("MainWindow", "prepare schematic update"))
        self.sortOrder.setItemText(0, _translate("MainWindow", "sort by x then y"))
        self.sortOrder.setItemText(1, _translate("MainWindow", "sort by y then x"))
        self.boardGroup.setTitle(_translate("MainWindow", "footprint properties"))
        self.xlabel.setText(_translate("MainWindow", "x position"))
        self.ylabel.setText(_translate("MainWindow", "y position"))
        self.unitslabel.setText(_translate("MainWindow", "units"))
        self.mmRadio.setText(_translate("MainWindow", "mm"))
        self.inchRadio.setText(_translate("MainWindow", "inch"))
        self.timestamplabel.setText(_translate("MainWindow", "timestamp"))
        self.footprintlabel.setText(_translate("MainWindow", "footprint ID"))
        self.schGroup.setTitle(_translate("MainWindow", "symbol properties"))
        self.schfilelabel.setText(_translate("MainWindow", "schematic file"))
        self.commitboardbutton.setText(_translate("MainWindow", "commit board"))
        self.writeSchematicButton.setText(_translate("MainWindow", "commit schematic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

